### ISSUE TITLE
0/10

### ISSUE THREAD

**Issue by firefl1es** [TheHowl/osuyooi#5]
Traceback (most recent call last):
  File "build.py", line 2, in <module>
    from scss import Compiler
ImportError: No module named 'scss'

**Comment by firefl1es** [comment]
PYTHON 3.4.3
ARCHLINUX

**Comment by TheHowl** [comment]
https://github.com/TheHowl/osuyooi/blob/master/README.md

>atm it doesn't seem to work after installing pyScss with pip install pyScss. I hope to fix it tho. At the moment you can, to make this run, download http://a.pomf.se/bfybtn.zip - put it in the osu!yooi folder and name it scss. check that in the scss folder there are the python files and not another subfolder named scss with inside the python files. now, you can build this!

you reminded me, though. pomf shut down. here you have an updated link: http://y.zxq.co/faslqq.zip
